version: '3.7'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: wirebarley
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123123
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
networks:
  app-network:
    driver: bridge
